name: pomodoro-brutalist-spa
version: 0.1.0
created: 2026-02-18

stack:
  package_manager: bun
  monorepo: false

  apps:
    web:
      framework: vite
      library: react
      language: typescript
      path: .

  backend:
    primary: convex
    enabled_in_mvp: false

  auth:
    provider: clerk
    enabled_in_mvp: false

  styling:
    framework: tailwindcss-v4
    ui_library: shadcn/ui
    animation: framer-motion
    theme: colorful-brutalist

  hosting:
    provider: vercel
    mode: spa

conventions:
  strict_typescript: true
  default_exports: false
  component_naming: PascalCase.tsx
  utility_naming: kebab-case.ts
  test_naming: "*.test.ts"

scripts:
  dev: bun run dev
  typecheck: bun run typecheck
  test: bun run test
  build: bun run build
  convex_dev: bun run convex:dev
  convex_codegen: bun run convex:codegen
